"""`multi-claude completion SHELL`：生成 bash / zsh / fish 补全脚本（方案 v0.2 §5.1.5）。

子命令与选项从 argparse 解析器遍历得到，避免手写清单与实际参数漂移。遍历用到
`parser._actions` 与 `argparse._SubParsersAction.choices` 两个未写入文档的属性，
兼容性由测试在 Python 3.8 与 3.12 上兜底。账号名在补全时调用 `multi-claude list --names` 获取。
本模块只输出脚本文本，不修改任何 shell 配置文件。
"""

import argparse
import shlex
from typing import Dict, List, NamedTuple

SHELLS = ("bash", "zsh", "fish")

# 第一个位置参数是账号名的子命令。
NAME_COMMANDS = ("migrate-default", "add", "proxy", "env", "args", "remove", "usage")
# 选项值是路径、应按文件补全的选项。
PATH_OPTIONS = ("-f", "--file", "--root", "--bin-dir", "--shared-dir")


class CommandSpec(NamedTuple):
    options: List[str]
    # 需要跟一个值的选项（补全时要跳过它的值，才能数对位置参数）
    value_options: List[str]


def collect(parser: argparse.ArgumentParser) -> Dict[str, CommandSpec]:
    """返回 {子命令: CommandSpec}；键 "" 表示顶层（尚未输入子命令时）。"""
    specs = {"": CommandSpec(_options(parser), [])}
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, sub in action.choices.items():
                specs[name] = CommandSpec(_options(sub), _value_options(sub))
    return specs


def _options(parser: argparse.ArgumentParser) -> List[str]:
    return [option for action in parser._actions for option in action.option_strings]


def _value_options(parser: argparse.ArgumentParser) -> List[str]:
    # nargs == 0 的是开关（store_true / help / version 等），其余选项都要跟值。
    return [option for action in parser._actions if action.option_strings and action.nargs != 0
            for option in action.option_strings]


def render(shell: str, parser: argparse.ArgumentParser) -> str:
    specs = collect(parser)
    if shell == "bash":
        return _bash(specs)
    if shell == "zsh":
        return _zsh(specs)
    return _fish(specs)


def _words(items: List[str]) -> str:
    return " ".join(items)


def _bash(specs: Dict[str, CommandSpec]) -> str:
    commands = sorted(name for name in specs if name)
    option_cases = "\n".join("    {}) opts={}; vopts={} ;;".format(
        name, shlex.quote(_words(spec.options)), shlex.quote(_words(spec.value_options)))
        for name, spec in sorted(specs.items()) if name)
    return """# bash completion for multi-claude (generated by `multi-claude completion bash`)
_multi_claude() {
  # COMP_WORDBREAKS 默认含 @ 与 :，COMP_WORDS 会把账号名 a@b 拆开，所以自己从 COMP_LINE 取完整的当前词。
  local line="${COMP_LINE:0:COMP_POINT}"
  local cur="${line##* }"
  local before="${line%%"$cur"}"
  local -a words
  read -r -a words <<< "$before"
  # 第一个不以 - 开头的词是子命令。
  local cmd="" i w
  for ((i = 1; i < ${#words[@]}; i++)); do
    if [[ "${words[i]}" != -* ]]; then cmd="${words[i]}"; break; fi
  done
  local opts="" vopts=""
  case "$cmd" in
%(option_cases)s
  esac
  # 数子命令之后已输入的位置参数个数，跳过选项与它的值；遇到 -- 记为 -1（args 的参数列表不补全）。
  local npos=0 skip=0 prev=""
  for ((i = i + 1; i < ${#words[@]}; i++)); do
    w="${words[i]}"
    if ((skip)); then skip=0; prev=""; continue; fi
    if [[ "$w" == "--" ]]; then npos=-1; break; fi
    if [[ "$w" == -* ]]; then
      if [[ " $vopts " == *" $w "* ]]; then skip=1; prev="$w"; fi
      continue
    fi
    ((npos++))
  done
  local candidates=""
  if ((skip)); then
    case "$prev" in
      %(path_options)s) COMPREPLY=($(compgen -f -- "$cur")); return 0 ;;
      *) COMPREPLY=(); return 0 ;;
    esac
  elif [[ -z "$cmd" ]]; then
    candidates="%(commands)s --help --version"
  elif ((npos < 0)); then
    COMPREPLY=(); return 0
  elif [[ "$cur" == -* ]]; then
    candidates="$opts"
  elif [[ "$cmd" == "completion" && $npos -eq 0 ]]; then
    candidates="%(shells)s"
  elif [[ " %(name_commands)s " == *" $cmd "* && $npos -eq 0 ]]; then
    candidates="$(multi-claude list --names 2>/dev/null)"
  elif [[ "$cmd" == "proxy" && $npos -eq 1 ]]; then
    candidates="off inherit"
  fi
  COMPREPLY=($(compgen -W "$candidates" -- "$cur"))
  # bash 只替换当前词最后一个分词字符之后的片段，候选要去掉同样长的前缀。
  local j prefix=""
  for ((j = ${#cur} - 1; j >= 0; j--)); do
    if [[ "$COMP_WORDBREAKS" == *"${cur:j:1}"* ]]; then prefix="${cur:0:j+1}"; break; fi
  done
  if [[ -n "$prefix" ]]; then
    for i in "${!COMPREPLY[@]}"; do COMPREPLY[i]="${COMPREPLY[i]#"$prefix"}"; done
  fi
}
complete -F _multi_claude multi-claude
""" % {"option_cases": option_cases, "commands": _words(commands), "shells": _words(list(SHELLS)),
       "name_commands": _words(list(NAME_COMMANDS)), "path_options": "|".join(PATH_OPTIONS)}


def _zsh(specs: Dict[str, CommandSpec]) -> str:
    commands = sorted(name for name in specs if name)
    option_cases = "\n".join("    {}) opts=({}); vopts=({}) ;;".format(
        name, _words([shlex.quote(o) for o in spec.options]),
        _words([shlex.quote(o) for o in spec.value_options]))
        for name, spec in sorted(specs.items()) if name)
    return """#compdef multi-claude
# zsh completion for multi-claude (generated by `multi-claude completion zsh`)
_multi_claude() {
  local cmd="" i w
  local -a opts vopts candidates
  # zsh 的 $words 不按 @ 分词，可直接使用；第一个不以 - 开头的词是子命令。
  for ((i = 2; i < CURRENT; i++)); do
    if [[ "${words[i]}" != -* ]]; then cmd="${words[i]}"; break; fi
  done
  case "$cmd" in
%(option_cases)s
  esac
  local npos=0 skip=0 prev=""
  for ((i = i + 1; i < CURRENT; i++)); do
    w="${words[i]}"
    if ((skip)); then skip=0; prev=""; continue; fi
    if [[ "$w" == "--" ]]; then npos=-1; break; fi
    if [[ "$w" == -* ]]; then
      if (( ${vopts[(Ie)$w]} )); then skip=1; prev="$w"; fi
      continue
    fi
    ((npos++))
  done
  local cur="${words[CURRENT]}"
  if ((skip)); then
    case "$prev" in
      %(path_options)s) _files; return ;;
      *) return ;;
    esac
  elif [[ -z "$cmd" ]]; then
    candidates=(%(commands)s --help --version)
  elif ((npos < 0)); then
    return
  elif [[ "$cur" == -* ]]; then
    candidates=($opts)
  elif [[ "$cmd" == "completion" && $npos -eq 0 ]]; then
    candidates=(%(shells)s)
  elif [[ " %(name_commands)s " == *" $cmd "* && $npos -eq 0 ]]; then
    candidates=(${(f)"$(multi-claude list --names 2>/dev/null)"})
  elif [[ "$cmd" == "proxy" && $npos -eq 1 ]]; then
    candidates=(off inherit)
  fi
  compadd -- $candidates
}
compdef _multi_claude multi-claude
""" % {"option_cases": option_cases, "commands": _words(commands), "shells": _words(list(SHELLS)),
       "name_commands": _words(list(NAME_COMMANDS)), "path_options": "|".join(PATH_OPTIONS)}


def _fish(specs: Dict[str, CommandSpec]) -> str:
    commands = sorted(name for name in specs if name)
    lines = [
        "# fish completion for multi-claude (generated by `multi-claude completion fish`)",
        "complete -c multi-claude -f",
        "function __multi_claude_positionals",
        "    # 输出当前子命令之后已输入的位置参数个数（跳过选项与它的值）；遇到 -- 输出 -1。",
        "    set -l tokens (commandline -opc)",
        "    set -l value_options $argv",
        "    set -l seen 0",
        "    set -l skip 0",
        "    set -l count 0",
        "    for token in $tokens[2..-1]",
        "        if test $seen -eq 0",
        "            if not string match -q -- '-*' $token",
        "                set seen 1",
        "            end",
        "            continue",
        "        end",
        "        if test $skip -eq 1",
        "            set skip 0",
        "            continue",
        "        end",
        "        if test \"$token\" = '--'",
        "            echo -1",
        "            return",
        "        end",
        "        if string match -q -- '-*' $token",
        "            if contains -- $token $value_options",
        "                set skip 1",
        "            end",
        "            continue",
        "        end",
        "        set count (math $count + 1)",
        "    end",
        "    echo $count",
        "end",
        "complete -c multi-claude -n __fish_use_subcommand -a {}".format(shlex.quote(_words(commands))),
        "complete -c multi-claude -n __fish_use_subcommand -l help -l version",
    ]
    for name, spec in sorted(specs.items()):
        if not name:
            continue
        condition = "__fish_seen_subcommand_from {}".format(name)
        for option in spec.options:
            flag = "-l {}".format(option[2:]) if option.startswith("--") else "-s {}".format(option[1:])
            requires = " -r" if option in spec.value_options else ""
            files = " -F" if option in PATH_OPTIONS else ""
            lines.append("complete -c multi-claude -n {} {}{}{}".format(
                shlex.quote(condition), flag, requires, files))
        vopts = _words(spec.value_options)
        if name in NAME_COMMANDS:
            lines.append("complete -c multi-claude -n {} -a '(multi-claude list --names 2>/dev/null)'".format(
                shlex.quote("{}; and test (__multi_claude_positionals {}) -eq 0".format(condition, vopts))))
        if name == "completion":
            lines.append("complete -c multi-claude -n {} -a {}".format(
                shlex.quote(condition), shlex.quote(_words(list(SHELLS)))))
        if name == "proxy":
            lines.append("complete -c multi-claude -n {} -a 'off inherit'".format(
                shlex.quote("{}; and test (__multi_claude_positionals {}) -eq 1".format(condition, vopts))))
    return "\n".join(lines) + "\n"
