"""`multi-claude completion SHELL`：生成 bash / zsh / fish 补全脚本（方案 v0.2 §5.1.5）。

子命令与选项从 argparse 解析器遍历得到，避免手写清单与实际参数漂移。遍历用到
`parser._actions` 与 `argparse._SubParsersAction.choices` 两个未写入文档的属性，
兼容性由测试在 Python 3.8 与 3.12 上兜底。账号名在补全时调用 `multi-claude list --names` 获取。
本模块只输出脚本文本，不修改任何 shell 配置文件。
"""

import argparse
import shlex
from typing import Dict, List, NamedTuple

SHELLS = ("bash", "zsh", "fish")

# 各子命令第 N 个位置参数的候选类型：name 账号名、dir 目录、file 文件、shell 补全的 shell 名、
# proxy 代理固定值、statusline 该子命令的动作。
POSITIONAL_KINDS = {
    "migrate-default": ["name"], "add": ["name"], "proxy": ["name", "proxy"], "env": ["name"],
    "args": ["name"], "remove": ["name"], "usage": ["name"], "completion": ["shell"],
    "route": ["dir", "name"], "which": ["dir"], "rename": ["name"], "mcp": ["name"],
    "statusline": ["statusline", "file"], "handoff": ["name"], "login": ["name"], "set": ["name"],
    "run": ["name"], "path": ["name"], "restore": ["name"],
}
# 选项值是路径、应按文件补全的选项。
PATH_OPTIONS = ("-f", "--file", "--root", "--bin-dir", "--shared-dir")
# 选项值是账号名的选项。
NAME_OPTIONS = ("--default", "--from", "--config-from")
FIXED_WORDS = {"shell": SHELLS, "proxy": ("off", "inherit"), "statusline": ("install", "uninstall")}


def _positional_cases(indent: str) -> str:
    """生成 `case "$cmd:$npos" in` 的分支，按候选类型合并。"""
    by_kind: Dict[str, List[str]] = {}
    for command, kinds in sorted(POSITIONAL_KINDS.items()):
        for index, kind in enumerate(kinds):
            by_kind.setdefault(kind, []).append("{}:{}".format(command, index))
    return "\n".join("{}{}) kind={} ;;".format(indent, "|".join(keys), kind) for kind, keys in sorted(by_kind.items()))


class CommandSpec(NamedTuple):
    options: List[str]
    # 需要跟一个值的选项（补全时要跳过它的值，才能数对位置参数）
    value_options: List[str]


def collect(parser: argparse.ArgumentParser) -> Dict[str, CommandSpec]:
    """返回 {子命令: CommandSpec}；键 "" 表示顶层（尚未输入子命令时）。"""
    specs = {"": CommandSpec(_options(parser), [])}
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, sub in action.choices.items():
                specs[name] = CommandSpec(_options(sub), _value_options(sub))
    return specs


def _options(parser: argparse.ArgumentParser) -> List[str]:
    return [option for action in parser._actions for option in action.option_strings]


def _value_options(parser: argparse.ArgumentParser) -> List[str]:
    # nargs == 0 的是开关（store_true / help / version 等），其余选项都要跟值。
    return [option for action in parser._actions if action.option_strings and action.nargs != 0
            for option in action.option_strings]


def render(shell: str, parser: argparse.ArgumentParser) -> str:
    specs = collect(parser)
    if shell == "bash":
        return _bash(specs)
    if shell == "zsh":
        return _zsh(specs)
    return _fish(specs)


def _words(items: List[str]) -> str:
    return " ".join(items)


def _bash(specs: Dict[str, CommandSpec]) -> str:
    commands = sorted(name for name in specs if name)
    option_cases = "\n".join("    {}) opts={}; vopts={} ;;".format(
        name, shlex.quote(_words(spec.options)), shlex.quote(_words(spec.value_options)))
        for name, spec in sorted(specs.items()) if name)
    return """# bash completion for multi-claude (generated by `multi-claude completion bash`)
_multi_claude() {
  # COMP_WORDBREAKS 默认含 @ 与 :，COMP_WORDS 会把账号名 a@b 拆开，所以自己从 COMP_LINE 取完整的当前词。
  local line="${COMP_LINE:0:COMP_POINT}"
  local cur="${line##* }"
  local before="${line%%"$cur"}"
  local -a words
  read -r -a words <<< "$before"
  # 第一个不以 - 开头的词是子命令。
  local cmd="" i w
  for ((i = 1; i < ${#words[@]}; i++)); do
    if [[ "${words[i]}" != -* ]]; then cmd="${words[i]}"; break; fi
  done
  local opts="" vopts=""
  case "$cmd" in
%(option_cases)s
  esac
  # 数子命令之后已输入的位置参数个数，跳过选项与它的值；遇到 -- 记为 -1（args 的参数列表不补全）。
  local npos=0 skip=0 prev=""
  for ((i = i + 1; i < ${#words[@]}; i++)); do
    w="${words[i]}"
    if ((skip)); then skip=0; prev=""; continue; fi
    if [[ "$w" == "--" ]]; then npos=-1; break; fi
    if [[ "$w" == -* ]]; then
      if [[ " $vopts " == *" $w "* ]]; then skip=1; prev="$w"; fi
      continue
    fi
    ((npos++))
  done
  local candidates="" kind=""
  if ((skip)); then
    case "$prev" in
      %(path_options)s) COMPREPLY=($(compgen -f -- "$cur")); return 0 ;;
      %(name_options)s) kind=name ;;
      *) COMPREPLY=(); return 0 ;;
    esac
  elif [[ -z "$cmd" ]]; then
    candidates="%(commands)s --help --version"
  elif ((npos < 0)); then
    COMPREPLY=(); return 0
  elif [[ "$cur" == -* ]]; then
    candidates="$opts"
  else
    case "$cmd:$npos" in
%(positional_cases)s
    esac
  fi
  case "$kind" in
    name) candidates="$(multi-claude list --names 2>/dev/null)" ;;
    dir) COMPREPLY=($(compgen -d -- "$cur")); return 0 ;;
    file) COMPREPLY=($(compgen -f -- "$cur")); return 0 ;;
    shell) candidates="%(shells)s" ;;
    proxy) candidates="off inherit" ;;
    statusline) candidates="install uninstall" ;;
  esac
  COMPREPLY=($(compgen -W "$candidates" -- "$cur"))
  # bash 只替换当前词最后一个分词字符之后的片段，候选要去掉同样长的前缀。
  local j prefix=""
  for ((j = ${#cur} - 1; j >= 0; j--)); do
    if [[ "$COMP_WORDBREAKS" == *"${cur:j:1}"* ]]; then prefix="${cur:0:j+1}"; break; fi
  done
  if [[ -n "$prefix" ]]; then
    for i in "${!COMPREPLY[@]}"; do COMPREPLY[i]="${COMPREPLY[i]#"$prefix"}"; done
  fi
}
complete -F _multi_claude multi-claude
""" % {"option_cases": option_cases, "commands": _words(commands), "shells": _words(list(SHELLS)),
       "positional_cases": _positional_cases("      "), "path_options": "|".join(PATH_OPTIONS),
       "name_options": "|".join(NAME_OPTIONS)}


def _zsh(specs: Dict[str, CommandSpec]) -> str:
    commands = sorted(name for name in specs if name)
    option_cases = "\n".join("    {}) opts=({}); vopts=({}) ;;".format(
        name, _words([shlex.quote(o) for o in spec.options]),
        _words([shlex.quote(o) for o in spec.value_options]))
        for name, spec in sorted(specs.items()) if name)
    return """#compdef multi-claude
# zsh completion for multi-claude (generated by `multi-claude completion zsh`)
_multi_claude() {
  local cmd="" i w
  local -a opts vopts candidates
  # zsh 的 $words 不按 @ 分词，可直接使用；第一个不以 - 开头的词是子命令。
  for ((i = 2; i < CURRENT; i++)); do
    if [[ "${words[i]}" != -* ]]; then cmd="${words[i]}"; break; fi
  done
  case "$cmd" in
%(option_cases)s
  esac
  local npos=0 skip=0 prev=""
  for ((i = i + 1; i < CURRENT; i++)); do
    w="${words[i]}"
    if ((skip)); then skip=0; prev=""; continue; fi
    if [[ "$w" == "--" ]]; then npos=-1; break; fi
    if [[ "$w" == -* ]]; then
      if (( ${vopts[(Ie)$w]} )); then skip=1; prev="$w"; fi
      continue
    fi
    ((npos++))
  done
  local cur="${words[CURRENT]}" kind=""
  if ((skip)); then
    case "$prev" in
      %(path_options)s) _files; return ;;
      %(name_options)s) kind=name ;;
      *) return ;;
    esac
  elif [[ -z "$cmd" ]]; then
    candidates=(%(commands)s --help --version)
  elif ((npos < 0)); then
    return
  elif [[ "$cur" == -* ]]; then
    candidates=($opts)
  else
    case "$cmd:$npos" in
%(positional_cases)s
    esac
  fi
  case "$kind" in
    name) candidates=(${(f)"$(multi-claude list --names 2>/dev/null)"}) ;;
    dir) _files -/; return ;;
    file) _files; return ;;
    shell) candidates=(%(shells)s) ;;
    proxy) candidates=(off inherit) ;;
    statusline) candidates=(install uninstall) ;;
  esac
  compadd -- $candidates
}
compdef _multi_claude multi-claude
""" % {"option_cases": option_cases, "commands": _words(commands), "shells": _words(list(SHELLS)),
       "positional_cases": _positional_cases("      "), "path_options": "|".join(PATH_OPTIONS),
       "name_options": "|".join(NAME_OPTIONS)}


def _fish(specs: Dict[str, CommandSpec]) -> str:
    commands = sorted(name for name in specs if name)
    lines = [
        "# fish completion for multi-claude (generated by `multi-claude completion fish`)",
        "complete -c multi-claude -f",
        "function __multi_claude_positionals",
        "    # 输出当前子命令之后已输入的位置参数个数（跳过选项与它的值）；遇到 -- 输出 -1。",
        "    set -l tokens (commandline -opc)",
        "    set -l value_options $argv",
        "    set -l seen 0",
        "    set -l skip 0",
        "    set -l count 0",
        "    for token in $tokens[2..-1]",
        "        if test $seen -eq 0",
        "            if not string match -q -- '-*' $token",
        "                set seen 1",
        "            end",
        "            continue",
        "        end",
        "        if test $skip -eq 1",
        "            set skip 0",
        "            continue",
        "        end",
        "        if test \"$token\" = '--'",
        "            echo -1",
        "            return",
        "        end",
        "        if string match -q -- '-*' $token",
        "            if contains -- $token $value_options",
        "                set skip 1",
        "            end",
        "            continue",
        "        end",
        "        set count (math $count + 1)",
        "    end",
        "    echo $count",
        "end",
        "complete -c multi-claude -n __fish_use_subcommand -a {}".format(shlex.quote(_words(commands))),
        "complete -c multi-claude -n __fish_use_subcommand -l help -l version",
    ]
    for name, spec in sorted(specs.items()):
        if not name:
            continue
        condition = "__fish_seen_subcommand_from {}".format(name)
        for option in spec.options:
            flag = "-l {}".format(option[2:]) if option.startswith("--") else "-s {}".format(option[1:])
            requires = " -r" if option in spec.value_options else ""
            files = " -F" if option in PATH_OPTIONS else ""
            names = " -a '(multi-claude list --names 2>/dev/null)'" if option in NAME_OPTIONS else ""
            lines.append("complete -c multi-claude -n {} {}{}{}{}".format(
                shlex.quote(condition), flag, requires, files, names))
        vopts = _words(spec.value_options)
        for index, kind in enumerate(POSITIONAL_KINDS.get(name, [])):
            at_position = shlex.quote("{}; and test (__multi_claude_positionals {}) -eq {}".format(
                condition, vopts, index))
            if kind == "name":
                source = "'(multi-claude list --names 2>/dev/null)'"
            elif kind == "dir":
                source = "'(__fish_complete_directories)'"
            elif kind == "file":
                source = "'(__fish_complete_path)'"
            else:
                source = shlex.quote(_words(list(FIXED_WORDS[kind])))
            lines.append("complete -c multi-claude -n {} -a {}".format(at_position, source))
    return "\n".join(lines) + "\n"
