"""启动命令 `<bin_dir>/claude-<名称>` 的生成与识别（方案 §5.1.4、§5.1.5）。

启动命令是由 config.json 推导出的产物，内容完全由账号名、身份、账号目录、代理、
额外环境变量和固定参数决定，所以“内容相同即 unchanged”就是幂等判断。第 2 行的受管标记
用来区分本工具生成的文件和用户自己的同名文件：没有标记的文件一律不覆盖、不删除。

`account_dir=` 那一行是 dir 身份账号的登录绑定依据（macOS 钥匙串服务名由它的 SHA-256 决定），
收敛引擎据此判断“会不会改变登录绑定”，所以该行的格式（`account_dir=` + shlex 转义值）
不能随意改动。
"""

import os
import shlex
from typing import Dict, List, Optional

from .config import IDENTITY_DEFAULT, PROXY_INHERIT, PROXY_OFF, PROXY_VARS
from .fsutil import KIND_FILE, entry_kind, read_text

MARKER_PREFIX = "# managed-by: multi-claude account="
LAUNCHER_PREFIX = "claude-"
LAUNCHER_MODE = 0o755
ACCOUNT_DIR_PREFIX = "account_dir="

_NO_PROXY_HOSTS = "localhost,127.0.0.1,::1"

# 在 shell 里导出后，会让通过任何启动命令启动的账号都改用这一份凭据（官方 env-vars 页的凭据变量），
# 账号各自的登录就被绕过了，所以启动命令一律清除。`env` 命令本来就拒绝这些键，不会再被设回来。
AUTH_OVERRIDE_ENV = ("ANTHROPIC_API_KEY", "ANTHROPIC_AUTH_TOKEN", "CLAUDE_CODE_OAUTH_TOKEN",
                     "CLAUDE_CODE_OAUTH_REFRESH_TOKEN")

# claude --help（2.1.286）中取可变个值的选项：会吞掉后面所有不以 `-` 开头的参数。
VARIADIC_OPTIONS = frozenset(["--add-dir", "--allowedTools", "--allowed-tools", "--betas", "--disallowedTools",
                              "--disallowed-tools", "--file", "--mcp-config", "--tools"])
# 同一版本中写作 `[value]` 的可选值选项：放在末尾且没有值时，会把 "$@" 的第一个参数当成自己的值。
OPTIONAL_VALUE_OPTIONS = frozenset(["-d", "--debug", "-r", "--resume", "-w", "--worktree", "--remote-control",
                                    "--from-pr", "--teleport", "--prompt-suggestions", "--cloud"])


def launcher_path(bin_dir: str, name: str) -> str:
    return os.path.join(bin_dir, LAUNCHER_PREFIX + name)


def expand_value(value: str) -> str:
    """值恰好是 `~` 或以 `~/` 开头时展开成绝对路径；其它写法（如 `--settings=~/x`）原样保留。"""
    if value == "~" or value.startswith("~/"):
        return os.path.expanduser(value)
    return value


def render(name: str, identity: str, account_dir: str, default_dir: str, proxy: str,
           env: Dict[str, str], args: List[str]) -> str:
    """生成 POSIX sh 启动命令的完整内容。所有值都经 shlex.quote 转义。

    account_dir 必须是 expand() 的结果（只展开 `~` 并转绝对路径，不做 realpath），
    因为 dir 身份账号的 macOS 登录绑定在这串字符上。default_dir 是 `$HOME/.claude` 展开后的路径，
    只在 default 身份下使用。
    """
    lines = [
        "#!/bin/sh",
        MARKER_PREFIX + name,
        "# Generated by multi-claude. Do not edit; use `multi-claude` commands to change it.",
        ACCOUNT_DIR_PREFIX + shlex.quote(account_dir),
        # claude 遇到不存在的配置目录会当成新账号，这里提前给出明确提示。
        'if [ ! -d "$account_dir" ]; then',
        # 用 printf 而不是 echo：dash 的 echo 会解释路径里的反斜杠。
        '  printf \'multi-claude: account directory does not exist: %s\\n\' "$account_dir" >&2',
        "  exit 1",
        "fi",
    ]
    lines.extend(_identity_lines(identity, default_dir))
    lines.append("unset " + " ".join(AUTH_OVERRIDE_ENV))
    for key in sorted(env):
        lines.append("{}={}; export {}".format(key, shlex.quote(expand_value(env[key])), key))
    lines.extend(_proxy_lines(proxy))
    command = ["exec", "claude"] + [shlex.quote(expand_value(arg)) for arg in args] + ['"$@"']
    lines.extend([
        "if ! command -v claude >/dev/null 2>&1; then",
        '  echo "multi-claude: claude not found in PATH" >&2',
        "  exit 127",
        "fi",
        " ".join(command),
        "",
    ])
    return "\n".join(lines)


def _identity_lines(identity: str, default_dir: str) -> List[str]:
    if identity == IDENTITY_DEFAULT:
        return [
            "default_dir=" + shlex.quote(default_dir),
            # default 身份靠“不设 CLAUDE_CONFIG_DIR”保住原登录，前提是 ~/.claude 仍指向账号目录；
            # 用户删掉或改指了这条软链时，直接运行会落到一个空目录，所以拒绝启动。
            # 用 cd -P + pwd -P 比较真实路径：[ -ef ] 不属于 POSIX，shellcheck 会报 SC3013。
            'if [ "$(cd -P -- "$default_dir" 2>/dev/null && pwd -P)" != "$(cd -P -- "$account_dir" && pwd -P)" ]; then',
            "  printf 'multi-claude: %s no longer points to %s; restore the link or run "
            "multi-claude migrate-default again\\n' \"$default_dir\" \"$account_dir\" >&2",
            "  exit 1",
            "fi",
            # 从别的账号的 Claude 会话里运行时会继承它的 CLAUDE_CONFIG_DIR，必须清掉才能落到默认账号。
            "unset CLAUDE_CONFIG_DIR CLAUDE_SECURESTORAGE_CONFIG_DIR",
        ]
    return [
        # 继承来的 CLAUDE_SECURESTORAGE_CONFIG_DIR 会改写钥匙串服务名的计算依据，必须清除。
        "unset CLAUDE_SECURESTORAGE_CONFIG_DIR",
        'CLAUDE_CONFIG_DIR="$account_dir"',
        "export CLAUDE_CONFIG_DIR",
    ]


def _proxy_lines(proxy: str) -> List[str]:
    if proxy == PROXY_INHERIT:
        # 不动任何代理变量，沿用启动时 shell 里的值。
        return []
    if proxy == PROXY_OFF:
        # 清掉全部 8 个变量；只是“不导出”挡不住从父进程继承来的代理。
        return ["unset " + " ".join(PROXY_VARS)]
    q_proxy = shlex.quote(proxy)
    return [
        "HTTPS_PROXY={0}; HTTP_PROXY={0}; https_proxy={0}; http_proxy={0}".format(q_proxy),
        "export HTTPS_PROXY HTTP_PROXY https_proxy http_proxy",
        # Claude 自己调用 git 时会退而使用 ALL_PROXY（方案 §3 依据 5）；清掉继承来的值，
        # 免得父进程里的另一个代理把部分流量带走。
        "unset ALL_PROXY all_proxy",
        # 在用户原有的 NO_PROXY 后追加本地地址，不覆盖用户原来的内网例外；原值为空时不留前导逗号。
        'NO_PROXY="${{NO_PROXY:+$NO_PROXY,}}{}"'.format(_NO_PROXY_HOSTS),
        'no_proxy="${{no_proxy:+$no_proxy,}}{}"'.format(_NO_PROXY_HOSTS),
        "export NO_PROXY no_proxy",
    ]


def variadic_warning(args: List[str]) -> Optional[str]:
    """固定参数的最后一个选项会吞掉运行时传入的参数时，返回告警文字；否则返回 None。

    `--allowedTools a b` 之后接 "$@"，用户传入的提示词或子命令会被当成工具名；
    `--resume` 之类的可选值选项放在末尾且没有值时，会把 "$@" 的第一个参数当成自己的值。
    """
    last_index = None
    for index, arg in enumerate(args):
        if arg.startswith("-"):
            last_index = index
    if last_index is None:
        return None
    option = args[last_index].split("=", 1)[0]
    has_values = last_index < len(args) - 1 or "=" in args[last_index]
    if option in VARIADIC_OPTIONS or (option in OPTIONAL_VALUE_OPTIONS and not has_values):
        return ("{} takes the arguments you pass to the launcher (a prompt or a subcommand) as its own "
                "values; put another option after it".format(option))
    return None


def rendered_account_dir(content: str) -> Optional[str]:
    """从启动命令内容里取出 `account_dir=` 行的值（已去掉 shlex 转义）；取不到时返回 None。"""
    for line in content.split("\n"):
        if line.startswith(ACCOUNT_DIR_PREFIX):
            try:
                parts = shlex.split(line[len(ACCOUNT_DIR_PREFIX):])
            except ValueError:
                return None
            return parts[0] if len(parts) == 1 else None
    return None


def managed_account(path: str) -> Optional[str]:
    """若 path 是本工具生成的启动命令，返回其中记录的账号名；否则返回 None。

    只认普通文件：软链、目录或读不出文本的文件都视为“不归本工具管理”。
    """
    if entry_kind(path) != KIND_FILE:
        return None
    content = read_text(path)
    if content is None:
        return None
    lines = content.split("\n", 2)
    if len(lines) < 2 or not lines[1].startswith(MARKER_PREFIX):
        return None
    return lines[1][len(MARKER_PREFIX):].strip() or None


def scan_managed(bin_dir: str) -> Dict[str, str]:
    """列出 bin_dir 中所有受管启动命令，返回 {账号名: 路径}。bin_dir 不存在时返回空。"""
    found: Dict[str, str] = {}
    try:
        names = os.listdir(bin_dir)
    except OSError:
        return found
    for entry in sorted(names):
        if not entry.startswith(LAUNCHER_PREFIX):
            continue
        path = os.path.join(bin_dir, entry)
        account = managed_account(path)
        if account is not None:
            found[account] = path
    return found
