"""按目录自动选账号（方案 feature-directory-routing §5.1.2）。

`claude-auto` 是由配置生成的 POSIX sh 入口：启动时取当前目录的物理路径，在规则目录里找最长的
“祖先或本身”，转交给对应账号的 `claude-<名称>`；没有命中时用默认账号，未设默认账号就直接运行 claude。
`resolve` 是同一算法的 Python 实现，供 `which` 使用；两者必须保持一致（测试会对拍）。
规则目录写进脚本时只展开 `~`，物理路径在启动时用 `cd -P` 求得，所以规则目录事后变成软链也能正确匹配。
"""

import os
import shlex
from typing import Optional, Tuple

from . import launcher
from .config import Account, Config, RouteRule
from .fsutil import KIND_FILE, KIND_MISSING, entry_kind, expand, read_text

ROUTER_NAME = "claude-auto"
# 与账号启动命令的标记（`# managed-by: multi-claude account=`）不同前缀：launcher.managed_account
# 不认它，apply 的孤儿清理就不会把它当成账号启动命令删掉；反之路由计划也只认这一行。
ROUTER_MARKER = "# managed-by: multi-claude router"
# 与路由入口同名的账号：两者的文件都是 <bin_dir>/claude-auto，不能共存。
RESERVED_ACCOUNT = "auto"


def router_path(bin_dir: str) -> str:
    return os.path.join(expand(bin_dir), ROUTER_NAME)


def is_router(path: str) -> bool:
    """path 是本工具生成的路由入口（普通文件，第 2 行为路由标记）。"""
    if entry_kind(path) != KIND_FILE:
        return False
    content = read_text(path)
    if content is None:
        return False
    lines = content.split("\n", 2)
    return len(lines) >= 2 and lines[1] == ROUTER_MARKER


def normalize_path(raw: str, cwd: str) -> str:
    """命令行输入的规则目录：`~` 开头的保持写法，其余转成绝对路径；都去掉尾部 `/`。"""
    if raw == "~" or raw.startswith("~/"):
        return raw.rstrip("/") or "~"
    return os.path.normpath(os.path.join(cwd, raw))


def resolve(config: Config, directory: str) -> Tuple[Optional[Account], Optional[RouteRule]]:
    """directory 会用哪个账号：返回 (账号或 None, 命中的规则或 None)。

    账号为 None 表示直接运行 claude；规则为 None 且账号非 None 表示用的是默认账号。
    与 claude-auto 一致：按物理路径比较，规则目录不存在时跳过，取最长，长度相同时靠前的规则优先。
    """
    here = os.path.realpath(directory)
    best_rule = None
    best_length = 0
    for rule in config.route_rules:
        target = expand(rule.path)
        # 对应脚本里的 `cd -P`：目录不存在或不可进入（无执行权限）时跳过。
        if not (os.path.isdir(target) and os.access(target, os.X_OK)):
            continue
        physical = os.path.realpath(target)
        # 逐字对应脚本的 case "$here/" in "$r"/*：规则目录解析成 / 时只命中 / 本身，与 sh 一致。
        if (here + "/").startswith(physical + "/") and len(physical) > best_length:
            best_rule, best_length = rule, len(physical)
    if best_rule is not None:
        return config.find(best_rule.account), best_rule
    if config.route_default is not None:
        return config.find(config.route_default), None
    return None, None


def _target_launcher(config: Config, name: str) -> str:
    # 用实际登记的大小写；找不到（用户手工改了 config.json）时原样使用，渲染不抛异常，由 apply 判冲突。
    account = config.find(name)
    return launcher.launcher_path(expand(config.bin_dir), account.name if account else name)


def render_router(config: Config) -> str:
    lines = [
        "#!/bin/sh",
        ROUTER_MARKER,
        "# Generated by multi-claude. Do not edit; use `multi-claude route` to change it.",
        "target=''",
    ]
    if config.route_rules:
        lines.extend([
            # 物理路径：经软链进入的目录与规则目录按同一标准比较。
            "here=$(pwd -P) || exit 1",
            "best=0",
        ])
    for rule in config.route_rules:
        lines.extend([
            # 规则目录不存在时 r 为空，该规则不参与匹配。
            "r=$(cd -P -- {} 2>/dev/null && pwd -P) || r=''".format(shlex.quote(expand(rule.path))),
            'if [ -n "$r" ]; then',
            '  case "$here/" in',
            # "$r"/* 带引号：路径里的 * ? [ 按字面匹配；末尾的 / 保证 /work 不会命中 /workshop。
            '    "$r"/*) if [ "${{#r}}" -gt "$best" ]; then best=${{#r}}; target={}; fi ;;'.format(
                shlex.quote(_target_launcher(config, rule.account))),
            "  esac",
            "fi",
        ])
    if config.route_default is not None:
        lines.extend([
            'if [ -z "$target" ]; then',
            "  target={}".format(shlex.quote(_target_launcher(config, config.route_default))),
            "fi",
        ])
    lines.extend([
        'if [ -n "$target" ]; then',
        # 绝对路径调用账号启动命令，不经 PATH 查找，避免被同名文件遮住。
        '  exec "$target" "$@"',
        "fi",
        "if ! command -v claude >/dev/null 2>&1; then",
        '  echo "multi-claude: claude not found in PATH" >&2',
        "  exit 127",
        "fi",
        'exec claude "$@"',
        "",
    ])
    return "\n".join(lines)


def router_status(config: Config) -> Optional[str]:
    """list / doctor 用：路由未启用时 None；否则 ok、missing、stale 或 conflict。"""
    if not config.routes_enabled:
        return None
    path = router_path(config.bin_dir)
    if entry_kind(path) == KIND_MISSING:
        return "missing"
    if not is_router(path):
        return "conflict"
    return "ok" if read_text(path) == render_router(config) and os.access(path, os.X_OK) else "stale"
